name: wt_widgetbook
description: The wt_widgetbook is for...
version: 0.0.2
publish_to: 'none' # To publish to pub.dev, remove this line
homepage: https://github.com/tmcmaster/wt_widgetbook

environment:
  sdk: '>=3.0.3 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: flutter analyze
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  coverage:
    generate: ./bin/generate_coverage.sh
    view: open coverage/html/index.html

dependencies:
  flutter:
    sdk: flutter
  ipsum: ^1.0.1
  widgetbook: ^3.1.0
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  json_annotation: "^4.8.1"
  json_serializable: